---
title: "32 bit vs 64 bit"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
# import data
library(readr)
dd <- read_delim("data.csv", ";", escape_double = FALSE, col_types = cols(workers = col_number()), trim_ws = TRUE)
library(data.table)
dd <- as.data.table(dd)
dd$platform <- as.factor(dd$platform)
dd$workers <- as.factor(dd$workers)
dd$benchmark <- as.factor(dd$benchmark)
dd$seconds <- as.numeric(dd$seconds)
dd$benchmark = with(dd, reorder(benchmark, seconds, median))

library(ggplot2)
library(scales)

# set theme
theme_set(theme_linedraw())

# plot 1
dd1 <- dd[, list(seconds=mean(seconds)), by=list(workers, platform)]
ggplot(dd1, aes(x=platform, y=seconds, fill=platform)) + geom_bar(stat="identity") + xlab("Platform") + ylab("Average Benchmark Duration (Seconds)")
# plot 2
dd2 <- dd[, list(seconds=mean(seconds)), by=list(benchmark, workers, platform)]
ggplot(dd2, aes(x=benchmark, y=seconds, fill=platform)) + geom_bar(stat="identity", position=position_dodge()) + xlab("Benchmark") + ylab("Average Benchmark Duration (Seconds)") + scale_x_discrete(labels = wrap_format(15))
```